# Generated by Django 4.1.3 on 2022-11-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rename_name_career_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampeonFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('runes', models.CharField(max_length=100)),
                ('explication', models.TextField()),
            ],
        ),
    ]
