# Generated by Django 4.1.3 on 2022-11-08 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_campeonfavorito'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CampeonFavorito',
            new_name='ChampFav',
        ),
    ]
