# Generated by Django 4.1.3 on 2022-11-08 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_rename_campeonfavorito_champfav'),
    ]

    operations = [
        migrations.AddField(
            model_name='champfav',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.user'),
        ),
    ]
