# Generated by Django 4.1.3 on 2022-11-10 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_career_user_user_career'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='career',
        ),
        migrations.DeleteModel(
            name='Career',
        ),
    ]
