# Generated by Django 4.1.3 on 2022-11-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_user_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Controller', 'Controller'), ('Duelist', 'Duelist'), ('Sentinel', 'Sentinel'), ('Initiator', 'Initiator')], max_length=255)),
                ('gender', models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman')], max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='career',
            field=models.CharField(max_length=100),
        ),
    ]
