# Generated by Django 4.1.3 on 2022-11-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_agent_alter_user_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='photo',
            field=models.ImageField(null=True, upload_to='agents'),
        ),
    ]
