# Generated by Django 4.1.3 on 2022-11-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_alter_agent_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='photo',
            field=models.ImageField(null=True, upload_to='agents'),
        ),
    ]
