# Generated by Django 4.1.3 on 2022-11-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_remove_agent_id_alter_agent_agent_alter_agent_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='photo',
            field=models.ImageField(null=True, upload_to='agents'),
        ),
    ]
